### ISSUE TITLE
Change to proper Semantic Versioning

### ISSUE THREAD

**Issue by luckytanuki** [KloxoNGCommunity/kloxoNG-CP#14]
Historically Kloxo has used version numbers that resembles the X.Y.Z (Major.Minor.Patch) format but it hasn't been properly implemented for Kloxo-MR. For the example the last release of Kloxo-MR is 7.0.0.c-2017091202. This violates proper Semantic Versioning as it doesn't indicate the many bug fix releases ( should increment  the Patch count) or changes to functionality and DB schema changes ( should increment a the Minor count).

To correctly adhere to the standard, the initial development version of KloxoNG should be 0.1.0 . The first release will be 1.0.0

See [Semantic Versioning 2.0.0](https://semver.org/) for more information.

**Comment by kloxoNG** [comment]
Created Tag for v0.1.0 and changed milestone v0.0.1 to v0.1.0
