### ISSUE TITLE
Move package names etc to variables/arrays at top of install php/scripts

### ISSUE THREAD

**Issue by dkstiler** [KloxoNGCommunity/kloxoNG-CP#19]
This is a needed step for us in order to have easier maintenance of the kloxo installation

**Comment by KimeraLive** [comment]
spell correction

**Comment by aalasolutions** [comment]
I am on it

**Comment by dkstiler** [comment]
We need to reopen while we need to fix the step2.inc file and also the installer.sh

**Comment by dkstiler** [comment]
It seems every hardcoded path and links are fixed , as it seems this issue is not applicable anymore, so  it is  closed
